"""PDF export service — generates professional travel itinerary PDFs."""
import io
from typing import Optional
from datetime import datetime


def generate_itinerary_pdf(
    destination: str,
    start_date: Optional[str],
    end_date: Optional[str],
    itinerary: Optional[dict],
    budget: Optional[dict],
    weather_info: Optional[dict],
    user_name: str = "Traveler",
) -> bytes:
    """
    Generate a professional PDF itinerary.
    Returns PDF bytes.
    Requires: pip install reportlab
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.colors import HexColor, white, black
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
            HRFlowable, KeepTogether,
        )
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=2 * cm,
            leftMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
        )

        # ── Colors ─────────────────────────────────────────────────────
        primary = HexColor("#1a3c5e")       # Deep navy
        accent = HexColor("#e67e22")        # Warm orange
        light_bg = HexColor("#f4f6f8")
        text_gray = HexColor("#555555")

        styles = getSampleStyleSheet()
        story = []

        # ── Title ──────────────────────────────────────────────────────
        title_style = ParagraphStyle(
            "Title", parent=styles["Title"],
            textColor=white, backColor=primary,
            fontSize=24, spaceAfter=0, spaceBefore=0,
            alignment=TA_CENTER, fontName="Helvetica-Bold",
            leading=32, borderPad=12,
        )
        subtitle_style = ParagraphStyle(
            "Subtitle", parent=styles["Normal"],
            textColor=white, backColor=primary,
            fontSize=12, alignment=TA_CENTER, fontName="Helvetica",
            leading=18,
        )

        story.append(Paragraph(f"Travel Itinerary: {destination}", title_style))
        story.append(Spacer(1, 0.2 * cm))

        date_range = f"{start_date or 'TBD'} to {end_date or 'TBD'}"
        story.append(Paragraph(f"Prepared for {user_name} | {date_range}", subtitle_style))
        story.append(Spacer(1, 0.5 * cm))

        generated_at = datetime.now().strftime("%B %d, %Y at %I:%M %p")
        story.append(Paragraph(
            f"<font color='gray' size='8'>Generated by AI Travel Planner Agent on {generated_at}</font>",
            ParagraphStyle("small", parent=styles["Normal"], alignment=TA_CENTER),
        ))
        story.append(HRFlowable(width="100%", thickness=2, color=accent, spaceAfter=12))

        heading_style = ParagraphStyle(
            "Heading", parent=styles["Heading2"],
            textColor=primary, fontName="Helvetica-Bold", fontSize=14, spaceBefore=14,
        )
        body_style = ParagraphStyle(
            "Body", parent=styles["Normal"],
            textColor=text_gray, fontSize=10, leading=15,
        )
        label_style = ParagraphStyle(
            "Label", parent=styles["Normal"],
            textColor=accent, fontName="Helvetica-Bold", fontSize=10,
        )

        # ── Budget Summary ──────────────────────────────────────────────
        if budget:
            story.append(Paragraph("Budget Summary", heading_style))
            pp = budget.get("per_person", {})
            total = budget.get("total_usd", 0)
            travelers = budget.get("travelers", 1)
            tier = budget.get("budget_tier", "mid-range").title()
            days = budget.get("duration_days", 1)

            budget_data = [
                ["Category", "Per Person (USD)", ""],
                ["Flights", f"${(pp.get('flight_usd') or 0):,.0f}", ""],
                ["Accommodation", f"${(pp.get('accommodation_usd') or 0):,.0f}", f"{days} nights"],
                ["Food & Dining", f"${(pp.get('food_usd') or 0):,.0f}", ""],
                ["Local Transport", f"${(pp.get('local_transport_usd') or 0):,.0f}", ""],
                ["Activities", f"${(pp.get('activities_usd') or 0):,.0f}", ""],
                ["Miscellaneous", f"${(pp.get('miscellaneous_usd') or 0):,.0f}", "10% buffer"],
                ["TOTAL (all travelers)", f"${(total or 0):,.0f}", f"{(travelers or 1)} traveler(s), {tier}"],
            ]
            t = Table(budget_data, colWidths=[8 * cm, 5 * cm, 4 * cm])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), primary),
                ("TEXTCOLOR", (0, 0), (-1, 0), white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("BACKGROUND", (0, -1), (-1, -1), accent),
                ("TEXTCOLOR", (0, -1), (-1, -1), white),
                ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -2), [light_bg, white]),
                ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#dddddd")),
                ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ]))
            story.append(t)
            story.append(Spacer(1, 0.4 * cm))

        # ── Day-by-Day Itinerary ─────────────────────────────────────────
        if itinerary and "days" in itinerary:
            story.append(Paragraph("Day-by-Day Itinerary", heading_style))

            for day in itinerary["days"]:
                day_num = day.get("day", "")
                day_title = day.get("title", "")
                day_date = day.get("date", "")

                day_header = Table(
                    [[f"Day {day_num}: {day_title}", day_date]],
                    colWidths=[13 * cm, 4 * cm],
                )
                day_header.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, -1), primary),
                    ("TEXTCOLOR", (0, 0), (-1, -1), white),
                    ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("ALIGN", (1, 0), (1, 0), "RIGHT"),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]))

                day_rows = []
                for period in ["morning", "afternoon", "evening"]:
                    slot = day.get(period, {})
                    if slot:
                        activity = slot.get("activity", "")
                        desc = slot.get("description", "")
                        cost = slot.get("cost_usd", 0)
                        tip = slot.get("tips", "")
                        period_str = period.title()
                        day_rows.append([
                            period_str,
                            f"{activity}\n{desc}",
                            f"${cost}",
                            tip,
                        ])

                if day_rows:
                    day_table = Table(
                        [["Time", "Activity", "Cost", "Tips"]] + day_rows,
                        colWidths=[2.5 * cm, 8 * cm, 2 * cm, 4.5 * cm],
                    )
                    day_table.setStyle(TableStyle([
                        ("BACKGROUND", (0, 0), (-1, 0), HexColor("#e8eef5")),
                        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                        ("FONTSIZE", (0, 0), (-1, -1), 8),
                        ("GRID", (0, 0), (-1, -1), 0.3, HexColor("#cccccc")),
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("LEFTPADDING", (0, 0), (-1, -1), 5),
                        ("TOPPADDING", (0, 0), (-1, -1), 4),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                        ("TEXTCOLOR", (0, 0), (-1, -1), text_gray),
                    ]))

                    # Meals
                    meals = day.get("meals", {})
                    meals_text = " | ".join([
                        f"Breakfast: {meals.get('breakfast', 'TBD')}",
                        f"Lunch: {meals.get('lunch', 'TBD')}",
                        f"Dinner: {meals.get('dinner', 'TBD')}",
                    ])

                    accommodation = day.get("accommodation", "")
                    daily_budget = day.get("daily_budget_usd", 0)

                    story.append(KeepTogether([
                        day_header,
                        Spacer(1, 0.1 * cm),
                        day_table,
                        Spacer(1, 0.1 * cm),
                        Paragraph(f"<b>Meals:</b> {meals_text}", body_style),
                        Paragraph(f"<b>Stay:</b> {accommodation} | <b>Daily Budget:</b> ${daily_budget}", body_style),
                        Spacer(1, 0.4 * cm),
                    ]))

        # ── Tips ────────────────────────────────────────────────────────
        if itinerary and "practical_tips" in itinerary:
            story.append(Paragraph("Practical Tips", heading_style))
            for tip in itinerary["practical_tips"]:
                story.append(Paragraph(f"• {tip}", body_style))
            story.append(Spacer(1, 0.3 * cm))

        # ── Weather ─────────────────────────────────────────────────────
        if weather_info and weather_info.get("best_time_to_visit"):
            story.append(Paragraph("Weather & Packing", heading_style))
            story.append(Paragraph(
                f"<b>Best time to visit:</b> {weather_info.get('best_time_to_visit', 'N/A')}",
                body_style,
            ))
            tips = weather_info.get("packing_tips", [])
            if tips:
                story.append(Paragraph("<b>Packing tips:</b>", label_style))
                for t in tips:
                    story.append(Paragraph(f"• {t}", body_style))

        # ── Footer ──────────────────────────────────────────────────────
        story.append(Spacer(1, 1 * cm))
        story.append(HRFlowable(width="100%", thickness=1, color=HexColor("#cccccc")))
        story.append(Paragraph(
            "This itinerary was generated by AI Travel Planner Agent. "
            "Always verify bookings and travel advisories before departure.",
            ParagraphStyle("footer", parent=styles["Normal"],
                           fontSize=7, textColor=HexColor("#999999"), alignment=TA_CENTER),
        ))

        doc.build(story)
        return buffer.getvalue()

    except ImportError:
        raise RuntimeError(
            "reportlab is not installed. Run: pip install reportlab"
        )
